# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-27 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_product_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('indication', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=200)),
                ('drug_form', models.CharField(max_length=200)),
                ('side_effects', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=50)),
                ('manufacture', models.CharField(max_length=200)),
                ('alternative_medicines', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
